version: '3'

services:
  app:
    image: javimosch/fiesta29:latest
    volumes:
      - "./public/upload:/app/public/upload"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    entrypoint: node
    command: index.js