version: '3'

services:
  app:
    image: javimosch/shareimgs:latest
    volumes:
      - "./public/upload:/app/public/upload"
    expose:
      - "3000"
    environment:
      - PORT: 3000
    env_file:
      - .env
    entrypoint: node
    command: index.js